<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TbcaTest.Application\TbcaTest.Application.csproj" />
      <ProjectReference Include="..\TbcaTest.CrossCutting\TbcaTest.CrossCutting.csproj" />
      <ProjectReference Include="..\TbcaTest.Domain\TbcaTest.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="FirebaseAdmin" Version="2.4.0" />
      <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    </ItemGroup>

</Project>


